- alias: roof_light_toggle
  trigger:
## Круглая кнопка
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000359b03a
      click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.relay_wall_switch_bedroom
      
- alias: light_off
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000359b03a
      click_type: hold
  action:
    - service: switch.turn_off
      entity_id: switch.relay_wall_switch_bedroom