- alias: Sunset light on
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - device_id: 318d1afd827c4fdc86e4fbd1555aad19
    domain: switch
    entity_id: switch.corridor_night_light_relay
    type: turn_on
  
- alias: 00_00_light_off
  description: ''
  trigger:
  - at: 00:00
    platform: time
  condition: []
  action:
  - device_id: 318d1afd827c4fdc86e4fbd1555aad19
    domain: switch
    entity_id: switch.corridor_night_light_relay
    type: turn_off
    
- id: '1592906061864'
  alias: corridor_light_online
  description: 'Включает свет в коридоре после отключения света(по подключению светильника)'
  trigger:
  - device_id: 405a2299aff74e56baeb458cd61c1e17
    domain: binary_sensor
    entity_id: binary_sensor.corridor_light
    platform: device
    type: connected
#   - event: start
#     platform: homeassistant
  condition:
  - condition: state
    entity_id: sun.sun
    state: sunset
  - before: 00:00
    condition: time
  - condition: device
    device_id: 405a2299aff74e56baeb458cd61c1e17
    domain: switch
    entity_id: switch.corridor_night_light_relay
    type: is_off
  action:
  - device_id: 405a2299aff74e56baeb458cd61c1e17
    domain: switch
    entity_id: switch.corridor_night_light_relay
    type: turn_on
