title: My Awesome Home

resources:
  - url: /community_plugin/canvas-gauge-card/canvas-gauge-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /community_plugin/bignumber-card/bignumber-card.js
    type: js
  - url: /community_plugin/atomic_calendar/atomic_calendar.js
    type: module
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: module
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: module

    
views:
  - !include lovelace/01_system.yaml
  - !include lovelace/02_westen.yaml
  - !include lovelace/03_light.yaml
  - !include lovelace/04_power.yaml
  - !include lovelace/05_ESPHome.yaml
#   - !include lovelace/.yaml